import type { RunReport, SourceStats } from "./types";

const CLONE_FLOOR_MIN = 30;

function sourceSection(name: string, s: SourceStats): string {
  const redactionLines =
    Object.keys(s.redactions).length === 0
      ? "  - none"
      : Object.entries(s.redactions)
          .sort((a, b) => b[1] - a[1])
          .map(([k, v]) => `  - ${k}: ${v}`)
          .join("\n");
  const skipped =
    s.skippedFiles.length === 0
      ? "  - none"
      : s.skippedFiles.map((f) => `  - ${f.file} — ${f.reason}`).join("\n");
  return `## ${name}

| metric | value |
|---|---|
| items parsed | ${s.itemsIn} |
| items kept | ${s.itemsKept} |
| chunks | ${s.chunks} (${s.privateChunks} private / ${s.publicChunks} public) |
| short messages dropped | ${s.shortDropped} |
| near-duplicates dropped | ${s.dedupDropped} |
| date coverage | ${s.dateMin ?? "—"} → ${s.dateMax ?? "—"} |

Redactions:
${redactionLines}

Files skipped:
${skipped}
${s.notes.length ? "\nNotes:\n" + s.notes.map((n) => `  - ${n}`).join("\n") : ""}`;
}

export function renderReport(r: RunReport): string {
  const audio =
    r.interviewAudioMinutes === null
      ? "interview source not run this pass"
      : `${r.interviewAudioMinutes.toFixed(1)} min recorded — ${
          r.interviewAudioMinutes >= CLONE_FLOOR_MIN
            ? `CLEARS the ${CLONE_FLOOR_MIN}-minute cloning floor`
            : `${(CLONE_FLOOR_MIN - r.interviewAudioMinutes).toFixed(1)} min BELOW the ${CLONE_FLOOR_MIN}-minute cloning floor`
        } (1–2 hours ideal)`;

  return `# Corpus build report

Generated: ${r.generatedAt}${r.dryRun ? " — **DRY RUN, nothing written**" : ""}
Sources run: ${r.sourcesRun.join(", ")}

## Totals

| metric | value |
|---|---|
| items kept | ${r.totals.items} |
| chunks written | ${r.totals.chunks} |
| private chunks | ${r.totals.private} |
| public chunks | ${r.totals.public} |
| holdout entries (sealed) | ${r.holdoutCount} |
| profile generated by | ${r.profileGeneratedBy ?? "—"} |

Interview audio: ${audio}

Redaction coverage note: regex rules cover keys/tokens, SSNs, card and account
numbers, emails, phone numbers, and street addresses. Free-text references to
third parties that match none of those patterns are NOT caught — review
private.jsonl before sharing anything derived from it.

${Object.entries(r.perSource)
  .map(([name, s]) => sourceSection(name, s))
  .join("\n\n")}
`;
}
